config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home' 
  get 'help' => 'static_pages#help' 
  get 'about' => 'static_pages#about' 
  get 'boadroom' => 'static_pages#boardroom' 
  get 'contact' => 'static_pages#contact' 
  get 'signup' => 'users#new' 
  get 'login' => 'sessions#new' 
  get 'users' => 'users#index'
  post 'login' => 'sessions#create' 
  delete 'logout' => 'sessions#destroy' 

  resources :users do 
    member do 
      get :following, :followers 
    end 
  end

  resources :account_activations, only: [:edit] 
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors_messages.html.erb
<% if @user.errors.any? %> 
<div id="error_explanation"> 
<div class="alert alert-danger"> The form contains 
<%= pluralize(@user.errors.count, "error") %> 
</div> <ul> <% @user.errors.full_messages.each do |msg| %>
 <li><%= msg %></li>
 <% end %> 
 </ul> 
 </div> 
 <% end %>

app/views/layouts/_footer.html.erb
<footer class="footer"> 
<small> KFX-SOCIAL</a> by
<a href="http://www.michaelhartl.com/">fatherShafiu</a> </small> 
<nav> <ul> <li><%= link_to "Github profile", 'https://github.com/fatherShafiu' %></li> 
<li><%= link_to "Contact", 'fathershafiu@gmail.com' %></li> 
<li><a href="https://twitter.com/FatherShafiu">News</a></li> 
</ul> 
</nav> 
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse"> 
<div class="container"> 

<nav> 

  <ul class="nav navbar-nav navbar-right"> 
  <%= link_to "kfx-social", root_path, id: "logo" %> 
   <li><%= link_to "Home", root_path %></li> 
   <li><%= link_to "Help", help_path %></li> 
   <% if logged_in? %> 
   <li><%= link_to "Users", users_path %></li> 
   <li class="dropdown"> 
   <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b> </a> 
   <ul class="dropdown-menu"> 
   <li><%= link_to "Profile", current_user %></li> <li><%= link_to "Settings", edit_user_path(current_user) %></li> 
   <li class="divider"></li> 
   <li> <%= link_to "Log out", logout_path, method: "delete" %> </li>
   </ul> 
   </li> 
   <% else %> 
   <li><%= link_to "Log in", login_path %></li> 
   <% end %> 
   </ul>
</nav> 
</div> 
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <div class="container">
    <%=render 'layouts/header'%>
    <div class="container"> 
    <% flash.each do |message_type, message| %> 
    <div class="alert alert-<%= message_type %>"><%= message %></div> 
    <% end %>
    <%= yield %>
    </div>
      <%=render 'layouts/footer'%>
      <%= debug(params) if Rails.env.development? %>

  </body>
</html>